### ISSUE TITLE
potential for adding metadata to pandas data frames

### ISSUE THREAD

**Issue by jsm296** [jupyterlab/jupyterlab-metadata-service#10]
In a discussion today with jupyter people about metadata support, it came up that it might be helpful to be able to add metadata to pandas data frames for use by the coding context in which they are instantiated (notebooks, for example).

A few links to discussion about associating metadata with a data table:

- in pandas: [https://stackoverflow.com/questions/14688306/adding-meta-information-metadata-to-pandas-dataframe](https://stackoverflow.com/questions/14688306/adding-meta-information-metadata-to-pandas-dataframe)
- in Julia: [https://github.com/JuliaData/DataFrames.jl/pull/1413](https://github.com/JuliaData/DataFrames.jl/pull/1413)

Looks like Julia might be close to supporting this, pandas currently does not but there are other Python options.

**Comment by saulshanabrook** [comment]
We should add an example of this, now that we can export metadata from a notebook. We should output a pandas dataframe along with some JSON LD describing it.
