### ISSUE TITLE
Review of current PRs

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab-metadata-service#11]
> For #6 and https://github.com/jupyterlab/jupyterlab-commenting/pull/10 (plus [this branch](https://github.com/jupyterlab/jupyterlab-commenting/tree/wip_backend_commenting)):

Hi! I really appreciate all the work that's going on here: this is a pretty big :elephant: to try to eat! I apologize for only having minutes between life things to contribute to this effort! I realize a lot of my comments are a bit "armchair architect"y: when I am doing open source, I am in fact usually sitting in an armchair, so I guess I'm entitled to such opinions. That aside, I got a good chunk of time all to myself last night/today and gave it a go at getting everything set up. I know everything is WIP, so please take these as coming from a desire to help the process along!

Things i could easily hack to get working, I mostly implemented as code on two toxic, should-never-be-merged, probably-won't-be-updated branches. My "results" are up and running on [binder](https://mybinder.org/v2/gh/bollwyvl/jupyterlab-metadata-service/add_apollo_graphql_webpack?urlpath=lab). 
- [meta](https://github.com/Quansight/jupyterlab-metadata-service/compare/add_graphql_apollo...bollwyvl:add_apollo_graphql_webpack?expand=1) (binder lives here)
- [commenting](https://github.com/jupyterlab/jupyterlab-commenting/compare/jupyterlab:wip_backend_commenting...bollwyvl:binder?expand=1)

## Metadata
- docs are inconsistent
- server is not implemented in typescript, so no code-reuse is possible
- server binds to `0.0.0.0`
- port is hardcoded
- isn't aware of baseurl
  - playground can be made to work, you have to append `?token=<token>` and refresh
- schema/source API is pretty duplicative and hardcoded
- shipping `node_modules` in a pip package is not an option
  - i've stolen lerna's tooling for building a standalone webpack(2!) build. also requires babel. ugh. but could be typescript... maybe
  - webpack can't deal with the `ws` package, but then...
- no subscriptions yet
- isn't playing nice with tokens/csrf yet (but will have to)
- don't rely on cdn for playground if using at all)
- should probably use lerna
  - i imagine the package laydown being something like:

| package | depends | note |
|-|-|-|
| `jsonld` | | all the jsonld types and contexts, wrapped in `.dts` a la [schema-dts](https://github.com/google/schema-dts) |
| `graphql`| `jsonld` | all the jsonld contexts, wrapped in `.dts` a la [apollo-codegen](https://github.com/apollographql/apollo-tooling#code-generation)
| `server` | `jsonld`, `graphql` | the server |
| `manager` | `graphql`, `jsonld` | just the apollo connection, wrapped in a `MetaDataManager` | 
| `manager-extension` | `manager` | just exposes `MetaDataManager` |
| `viewer` | `jsonld` | the top-level metadata viewer which can show multiple views |
| `viewer-extension` | `viewer`, `manager` | expose the viewer token |
| `viewer-form` | `viewer` | `react-jsonschema-form` view provider |
| `viewer-table` | `viewer` | phosphor data grid view provider (might just be JSON-LD frame -> explorer) |
- all that being said, i _still_ think the reference implementation server should be done in python... but i would still validate my types directly against a _known_, checked-in schema, and all the tooling for that is homed in `node`, but then it's a *development time* concern, and not a *every-single-user's computer-at-all-times* concern.

## Commenting
- doesn't really seem to do anything once i get it loaded? 
  - i put in my name, and click the `+` and the `<-` but nothing happens
- bootstrap messes with lab styling: we just bought 0.5MB of [blueprint](https://github.com/jupyterlab/jupyterlab/pull/5538), so i guess use that
- uses `http://api.github` (breaks on binder)
- i (and the server) don't understand the distinction between threads and annotations... the `domain` of annotation should be _anything_ that implements some minimal interface (probably just `id`).

## GraphQL Schema
- the graphql is buried inside `gql` tags in the js files
  - move out to `.graphql` files, in their own package, have types generated, use fragments, etc.
    - but then, these are going to need to be generated anyway, as there are hundreds of classes to manage
- we're gonna need some Union types real quick
- adopt the [Relay](https://facebook.github.io/relay/docs/en/graphql-server-specification.html) interface.
  - absolutely use `Node`
    - `id` should be opaque
  - probably also use  `Connection` for pagination (though it makes the queries much uglier)
  - make a `createNode` mutation which reuses all the existing types
- get subscriptions working sooner rather than later

Cheers, and good luck!

**Comment by saulshanabrook** [comment]
@bollwyvl Thanks for all the feedback! 👍

To give some more transparency on our internal cycle, we are prepping for a live demo presentation of the work in a couple of weeks. During that time we will be focused on putting that together, and the some of the refactoring/best practices work will be in on the back burner.

After that, we plan to swoop around and do some of this more level level work. I expect your suggestions here will be helpful for that! And hopefully we can engage back and forth with you here on the approach.

**Comment by saulshanabrook** [comment]
> Things i could easily hack to get working, I mostly implemented as code on two toxic, should-never-be-merged, probably-won't-be-updated branches.

The [commenting](https://github.com/jupyterlab/jupyterlab-commenting/compare/jupyterlab:wip_backend_commenting...bollwyvl:binder?expand=1) doesn't look like that invasive of a change.  @hoo761 @karamba228 If it is helpful to you both, you could take a look at it and see what's useful.

In the [metadata](https://github.com/Quansight/jupyterlab-metadata-service/compare/add_graphql_apollo...bollwyvl:add_apollo_graphql_webpack?expand=1) am I understanding it right that you are using webpack to build the server and then just shipping those files?

**Comment by bollwyvl** [comment]
> transparency

thanks for the update! excited for you to impress... whoever it is! i hope said demo will be available on binder, as having stuff run there is the best counter to WFM without doing the full CI dance.

> engage back and forth

yeah, i'm here for you... i just disappear for days at a time because of work/life.

> using webpack to build the server and then just shipping those _files_

that _file_ :stuck_out_tongue_closed_eyes:. i left it as a directory for the potential of a config-file-of-last-resort or whatever, but it needs to be as simple as stones. I don't have any suggestions for a shim of `ws` that will work in webpack, but if you're :running_woman: :running_man: :horse_racing: for a demo, don't try and put subscriptions in, no matter _how_ you plan to distribute it!

**Comment by saulshanabrook** [comment]
> thanks for the update! excited for you to impress... whoever it is! i hope said demo will be available on binder, as having stuff run there is the best counter to WFM without doing the full CI dance.

Yeah it's currently a huge pain to get everything working together, especially because it requires jupyterlab master. 

The [databus](https://github.com/jupyterlab/jupyterlab/pull/5857) work is actually a bit easier to try out, since it a PR to core itself.

> for a demo, don't try and put subscriptions in, no matter _how_ you plan to distribute it!

Duly noted!

**Comment by saulshanabrook** [comment]
@bollwyvl Here is a link to the demo repo, which works in binder https://github.com/jupytercalpoly/rich-context-demo if you would like to play with it. 

If you click on data within `data` folder there is metadata registered for them.

**Comment by bollwyvl** [comment]
Woo! Congrats! Checking it out now!

**Comment by saulshanabrook** [comment]
Closing this since the codebase has changed since this was added.
