### ISSUE TITLE
Preparing for the Metadata Explorer UI demo

### ISSUE THREAD

**Issue by acu192** [jupyterlab/jupyterlab-metadata-service#12]
In order to fulfill the needs of the Metadata Explorer demo (see mockups [here](https://www.figma.com/file/gz2J72S4S6BEqwBYh0sh91NT/Commenting-and-Annotations-for-Data-Sets.?node-id=303%3A1)), we need to add 8 new fields to the dataset schema (i.e. [this file](https://github.com/jupyterlab/jupyterlab-metadata-service/blob/master/backend/jupyterlab_metadata_service_server/src/schemas/dataset.js)) following the schema for the `Dataset` type outlined [in schema.org's Dataset type](https://schema.org/Dataset).

Those 8 fields that need to be added are:
- copyrightHolder
- copyrightYear
- creator
- license
- provider
- dateCreated
- dateModified
- exampleOfWork

Next we need to publish a method for retrieving the metadata given a `target` (i.e. a string representing a file path to, presumably, a data file). The interface should be [here](https://github.com/jupyterlab/jupyterlab-metadata-service/blob/master/frontend/src/metadata_iface/datasets.ts), and the implementation [here](https://github.com/jupyterlab/jupyterlab-metadata-service/blob/master/frontend/src/metadata_concrete/datasets.ts).

**Comment by saulshanabrook** [comment]
This sounds good.

> Next we need to publish a method for retrieving the metadata given a `target` (i.e. a string representing a file path to, presumably, a data file).

Could be a string for the URL? So for a file this would be `file:///data.csv` for example.

**Comment by acu192** [comment]
Yeah, I was imagine the same as we did for the commenting `target`. ([here](https://github.com/jupyterlab/jupyterlab-metadata-service/blob/d26752d14fe1f433708dc000a9b79d12e017ae13/frontend/src/metadata_iface/comments.ts#L24))

I'll start working on the UI assuming we have these fields, and we can plug them in once they exist.

**Comment by xmnlab** [comment]
sounds pretty good. I will add this fields today. I am also studying how feasible is the integration with https://github.com/cape-io/graphql-schema-org .. but for now I will just add this fields in the schema type/resolver/datasource.

**Comment by xmnlab** [comment]
@acu192 do you could understand the difference between "author" and "creator" ? should we keep both?

**Comment by acu192** [comment]
@xmnlab Good point. On the `Dataset` page, under `creator` it says "This is the same as the Author property for CreativeWork."  (Also note that `Dataset` derives from `CreativeWork`.)

Therefore I would say we don't need `creator`. Unless others point out something we're not seeing...

**Comment by xmnlab** [comment]
@acu192 I added both for now ... we can remove any one any time https://github.com/jupyterlab/jupyterlab-metadata-service/pull/13

I will added the code for frontend there.
