### ISSUE TITLE
Determine how to store Annotation's `resolved` field

### ISSUE THREAD

**Issue by acu192** [jupyterlab/jupyterlab-metadata-service#15]
Currently, [`resolved` is a field on the Annotation type](https://github.com/jupyterlab/jupyterlab-metadata-service/blob/06c437bcab2b1a4547dc5de5f5e77a7644ab5327/backend/jupyterlab_metadata_service_server/src/schemas/annotation.js#L14).

However the `resolved` field is not standard in the [W3C Annotation Data Model](https://www.w3.org/TR/annotation-model/).

We need to revisit this at some point to see if there is a standard way to store the "resolved" concept.

**Comment by bollwyvl** [comment]
Seems like a decently data-model relevant choice would be another
annotation, where the target is the original annotation:

    {
      "type": "TextualBody",
      "value": "resolved",
      "purpose": "tagging"
    }

**Comment by saulshanabrook** [comment]
Closing this since we aren't specifying annotation types directly now.
