### ISSUE TITLE
Installing Extension

### ISSUE THREAD

**Issue by koliphan2** [jupyterlab/jupyterlab-metadata-service#29]
When starting a new environment and installing jupyterlab, then going straight to the Metadata Service Extension, the instructions provided for installation do not work. 

> jupyter labextension install @jupyterlab/metadata

When the code above is entered, this error appears:

<img width="632" alt="Screen Shot 2019-08-12 at 6 24 37 PM" src="https://user-images.githubusercontent.com/35544523/62907156-1da55d80-bd2f-11e9-8cca-87e858a5a60f.png">

Perhaps this is an issue with where I am doing the code. Where is this supposed to be done? (In relation to the Jupyterlab install code)

Going to the development instructions to see if I can instead do that, and then running jupyter labextension link .  gives a  ‘failed to build’ run time error as well.

**Comment by jasongrout** [comment]
What does that error file say?

**Comment by koliphan2** [comment]
The log file? 

<img width="1097" alt="Screen Shot 2019-08-12 at 8 15 02 PM" src="https://user-images.githubusercontent.com/35544523/62910584-48e37900-bd3e-11e9-9a6d-45cbf87673e0.png">

It also mentions that a complete log of this run can be found elsewhere, so I'll also provide that  in case it's needed. 

<img width="1169" alt="Screen Shot 2019-08-12 at 8 19 27 PM" src="https://user-images.githubusercontent.com/35544523/62910642-8811ca00-bd3e-11e9-9b1b-b46afcf43f6d.png">

**Comment by saulshanabrook** [comment]
I will look into this, thank you for opening an issue.

**Comment by saulshanabrook** [comment]
Ah, the issue is that the package name is `@jupyterlab/metadata-extension`. Try this?

```bash
jupyter labextension install @jupyterlab/metadata-extension @jupyterlab/dataregistry-extension
```

**Comment by koliphan2** [comment]
I just attempted this again to check and see if it is working, but it is not. When trying to install the extension within the jupyterlab page, it is able to install the data registry and rebuild just fine, but the metadata one is still not working properly within the lab. 
![image](https://user-images.githubusercontent.com/35544523/64083462-b7807a80-ccdd-11e9-9029-165c8996b59f.png)

When trying to install in within the terminal, a KeyError is given. '@jupyterlab/apputils'.
The log file gives the details.
![image](https://user-images.githubusercontent.com/35544523/64083464-bd765b80-ccdd-11e9-911b-d75544d8531c.png)

**Comment by saulshanabrook** [comment]
Could you try upgrading `jupyterlab`? `pip install -U jupyterlab`
