### ISSUE TITLE
Initial repo setup

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-metadata-service#3]
This is an issue to track the initial repository setup:

- [x] Add official Jupyter copyright and license.
- [x] Add standard sections to README, including team section.
- [x] Create skeleton for single npm package
- [x] Create JLab style labels.

**Comment by saulshanabrook** [comment]
@xmnlab This is a good place to start for this repo, especially the skeleton NPM package.

**Comment by xmnlab** [comment]
thanks @saulshanabrook I am going do it today :)

**Comment by saulshanabrook** [comment]
>  Create JLab style labels.

@ellisonbg What do you mean by this?

**Comment by xmnlab** [comment]
I will create issues based on jlab labels. for now I will start with `status` and `type`.

Status:

- [x] status:Blocked
- [x] status:Design Completed
- [x] status:Duplicate
- [x] status:Inactive
- [x] status:Invalid
- [x] status:Needs Discussion
- [x] status:Needs Info
- [x] status:Needs Review
- [x] status:Needs User Testing
- [x] status:Stubborn
- [x] status:Wont Fix
- [x] status:Work in Progress

Types:

- [x] type:Bug
- [x] type:Enhancement
- [x] type:Feedback
- [x] type:Maintenance
- [x] type:Question

**Comment by xmnlab** [comment]
@ellisonbg 

these labels was created (https://github.com/jupyterlab/jupyterlab-metadata-service/labels)

if you have any comment about labels, let me know.

if all initial items is OK for you, we can close this issue.

**Comment by xmnlab** [comment]
I think we can remove this information from License: https://github.com/jupyterlab/jupyterlab-metadata-service/blob/f4e4d0f72bccbc674e6e3b66aec661c14ab59ec9/LICENSE#L29

**Comment by xmnlab** [comment]
could we close this issue?
