### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by Zsailer** [jupyterlab/jupyterlab-metadata-service#48]
(Sorry for the delay on this, @saulshanabrook!) 

I'll add some items to this checklist as I go. I'll submit PRs too :)

- [ ] Developer docs `jupyterlab extension link ...` command point to outdated paths. 
     - `../jupyterlab-data-explorer/dataregistry-extension/` becomes `../jupyterlab-data-explorer/packages/dataregistry-extension/`
     - ` ../jupyterlab-data-explorer/dataregistry/` becomes ` ../jupyterlab-data-explorer/packages/dataregistry/`

**Comment by saulshanabrook** [comment]
Ah thanks! Yeah that was a pretty recent change. This won't even work at the moment with the new packages I believe.

**Comment by Zsailer** [comment]
Ah, you're right! I had to install the dev version using the contributing docs on the data-explorer.

**Comment by saulshanabrook** [comment]
We should probably change the docs here to not use the dev version of the data explorer, instead just use the published version, like this:

https://github.com/jupyterlab/jupyterlab-metadata-service/blob/a7387c05ab5c8999f9cacd4a485af84fe26f31f5/.github/workflows/test.yml#L16

**Comment by saulshanabrook** [comment]
@kgryte at some point we should publish the new packages from the data registry and update this to depend on them. I guess until then we can just remove the instructions for installing both from master and just use the release version of the data registry?

**Comment by kgryte** [comment]
Agreed.

**Comment by kgryte** [comment]
Also, presumably, we should only be encouraging contributors to be working off the release version anyway, as this is what this extension depends on.

**Comment by kgryte** [comment]
Submitted a PR to address the setup instructions: https://github.com/jupyterlab/jupyterlab-metadata-service/pull/50
