### ISSUE TITLE
Add user facing documentation

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab-metadata-service#52]
We should add some user facing documentation that outlines how to use this plugin.

**Comment by tgeorgeux** [comment]
# Outline:
- [ ] Intro: This is an exploration, not the end product.
- [ ] Installation & Updating installation (jupyterlab extension update)
    - [ ] Connecting to the Data Registry
- [ ] Introduction to Linked Data.
    - [ ] Reference out to [linked data](https://json-ld.org/)
    - [ ] Show Datasets.yaml file 
- [ ] How to navigate the Graph.
    - [ ] Click links.
    - [ ] Manual URL input.

**Comment by saulshanabrook** [comment]
https://json-ld.org/
