### ISSUE TITLE
Discussions with schema.org folks

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-metadata-service#7]
@fperez and I had a talk with R. V. Guha who works on schema.org and the data commons. Looks like there is interest in getting a group together to work through adding additional capabilities to the schema.org schema for datasets, notebooks, source code files, etc. Will post more as details emerge.

**Comment by bollwyvl** [comment]
Very exciting stuff! Yes please do keep us updated here! I'd be happy to participate in whatever discussions move forward, having been down this [road a few times](https://gist.github.com/bollwyvl/6edda34649ba4b5cbaf9)!

First, I'd like to point out that as of recent-ish developments in the standards, the notebook format v4 could now be considered "Linked Data Ready": the last roadblocks, our mixed semi-private, semi-junk-draw `metadata` fields, are now [possible to describe for linked data](https://nbviewer.jupyter.org/gist/4d503fba51d6760f2782d099e4285ecf). This means we can _fiat_ a schema-conforming `v4` document as having a robust meaning in schema.org sense of _meaning_, while `v5` would require very little modification to support extensible linked data features like string-level internationalization.

It seems like a `ComputableDigitalDocument` (as a kind of `CreativeWork`, `DigitalDocument`) is long overdue to join `SpreadsheetDigitalDocument` (potentially as an ancestor), with whatever the JSON encoding of a notebook would actually be as `NotebookDigitalDocument`. Even getting the `CreativeWork` metadata would already be really handy.

Our kernelspecs are cool and everything, but Linked Data is probably the technology best suited to actually capturing The Environment Problem: we can't just shout MIMETYPES and say it's going to be alright. While this is an nbformat v5 kind of thing, it's probably good to have on the table during discussions.

Of course, schema.org still isn't really "publication grade," for folks like Nature, Science, etc. which prefer W3C standards and incumbent taxonomies like Dublin Core, but _sometimes_ schema.org uses those, so it's a good step forward for making notebooks more discoverable, if not any more computable or citeable.

Hooray!

**Comment by saulshanabrook** [comment]
Closing this for now, since we support multiple taxonomies.
